name: Auto Build & Deploy

on:
  push:
    branches:
      - main  # Runs on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install  # Ensure `package.json` exists in the repo

      - name: Build project
        run: npm run build  # This should be defined in your `package.json` scripts

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: build  # Adjust if your build output directory is different

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download built files
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: build

      - name: Deploy to Server (via SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/myapp  # Adjust to your server project directory
            git pull origin main
            npm install  # Install/update dependencies
            npm run build  # Rebuild the project
            pm2 restart myapp || pm2 start npm --name "myapp" -- run start
